// Scans a Godot project and writes src/registry.gen.ts: every texture, scene and script
// as a res:// string literal, so a path typo becomes an ordinary TypeScript error.
//
// Usage: bun tools/gen-registry.ts <projectRoot> [--out <file>] [--watch]     (Node built-ins only: fs, path, url)
//   --out   where to write the generated file (default: src/registry.gen.ts next to this tool). A game that uses
//           this tool as a submodule should point it at its own folder, not write inside the submodule.

import { existsSync, mkdirSync, readFileSync, readdirSync, watch, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

let OUTPUT = fileURLToPath(new URL("../src/registry.gen.ts", import.meta.url)); // --out overrides it
const SKIP_DIRS = new Set([".godot", "node_modules", ".git"]);

const KINDS = [
  { name: "Textures", type: "TexturePath", exts: [".png", ".jpg", ".jpeg", ".webp", ".svg"] },
  { name: "Scenes", type: "ScenePath", exts: [".tscn"] },
  { name: "Scripts", type: "ScriptPath", exts: [".gd"] },
];

// ---- 1. scan: every file under the project as a res:// path, sorted --------------------------

// Godot itself ignores a folder that has its own project.godot (a separate project) or a .gdignore file.
// The registry must too, or a submodule such as engine/ would fill a game's registry with its sample files.
const belongsToAnotherWorld = (dir: string) => existsSync(join(dir, "project.godot")) || existsSync(join(dir, ".gdignore"));

function scan(root: string): string[] {
  const found: string[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        const sub = join(dir, entry.name);
        if (!SKIP_DIRS.has(entry.name) && !belongsToAnotherWorld(sub)) walk(sub);
      } else if (!entry.name.endsWith(".import")) {
        // backslashes -> forward slashes so Windows gives the same res:// paths
        found.push("res://" + relative(root, join(dir, entry.name)).split(sep).join("/"));
      }
    }
  };
  walk(root);
  return found.sort(); // plain code-unit order: the same on every machine
}

// ---- 2. keys: camelCased file stems; folder (then extension) added on a collision -------------

const words = (s: string) => s.split(/[^A-Za-z0-9]+/).filter(Boolean);
const stemWords = (p: string) => words(basename(p, extname(p)));
const folderWords = (p: string) => words(dirname(p.slice("res://".length)));

function camel(ws: string[]): string {
  const key = ws.map((w, i) => (i === 0 ? w[0].toLowerCase() : w[0].toUpperCase()) + w.slice(1)).join("");
  if (key === "") return "_";
  return /^[0-9]/.test(key) ? "_" + key : key;
}

function assignKeys(paths: string[]): [path: string, key: string][] {
  const strategies = [
    (p: string) => stemWords(p), //                                    ball
    (p: string) => [...folderWords(p), ...stemWords(p)], //            artBall
    (p: string) => [...folderWords(p), ...stemWords(p), extname(p).slice(1)], // artBallPng
  ];
  const level = new Map(paths.map((p) => [p, 0]));
  const keyOf = (p: string) => camel(strategies[level.get(p)!](p));

  // whoever shares a key with someone else moves to the next, more specific strategy
  for (let round = 1; round < strategies.length; round++) {
    const byKey = new Map<string, string[]>();
    for (const p of paths) byKey.set(keyOf(p), [...(byKey.get(keyOf(p)) ?? []), p]);
    for (const group of byKey.values()) {
      if (group.length > 1) group.forEach((p) => level.set(p, level.get(p)! + 1));
    }
  }

  // last resort (e.g. art/a_b/c.png vs art/a/b_c.png): number the later ones
  const used = new Map<string, number>();
  return paths.map((p) => {
    const key = keyOf(p);
    const n = (used.get(key) ?? 0) + 1;
    used.set(key, n);
    return [p, n === 1 ? key : `${key}${n}`];
  });
}

// ---- 3. render and write (only if the text changed, so watchers aren't retriggered) ----------

function render(allPaths: string[]): string {
  const out = ["// AUTO-GENERATED by tools/gen-registry.ts. Do not edit."];
  for (const kind of KINDS) {
    const paths = allPaths.filter((p) => kind.exts.includes(extname(p).toLowerCase()));
    if (paths.length === 0) {
      out.push(`export const ${kind.name} = {} as const;`);
    } else {
      out.push(`export const ${kind.name} = {`);
      for (const [path, key] of assignKeys(paths)) out.push(`  ${key}: ${JSON.stringify(path)},`);
      out.push("} as const;");
    }
    out.push(`export type ${kind.type} = (typeof ${kind.name})[keyof typeof ${kind.name}];`, "");
  }
  return out.join("\n");
}

function generate(root: string): boolean {
  const next = render(scan(root));
  if (existsSync(OUTPUT) && readFileSync(OUTPUT, "utf8") === next) return false;
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, next);
  return true;
}

// ---- 4. command line ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const outIndex = args.indexOf("--out");
const rootArg = args.find((a, i) => !a.startsWith("--") && (outIndex < 0 || i !== outIndex + 1));
if (!rootArg || !existsSync(join(rootArg, "project.godot")) || (outIndex >= 0 && !args[outIndex + 1])) {
  console.error("usage: bun tools/gen-registry.ts <projectRoot> [--out <file>] [--watch]   (projectRoot has project.godot)");
  process.exit(1);
}
if (outIndex >= 0) OUTPUT = resolve(args[outIndex + 1]);
const root = resolve(rootArg);

console.log(generate(root) ? `wrote ${OUTPUT}` : `unchanged ${OUTPUT}`);

if (args.includes("--watch")) {
  let timer: ReturnType<typeof setTimeout> | undefined;
  watch(root, { recursive: true }, (_event, filename) => {
    if (filename && filename.split(/[\\/]/).some((part) => SKIP_DIRS.has(part))) return;
    clearTimeout(timer);
    timer = setTimeout(() => console.log(generate(root) ? `regenerated ${OUTPUT}` : "unchanged"), 100);
  });
  console.log(`watching ${root} (ctrl-c to stop)`);
}
