// AUTO-GENERATED by tools/gen-registry.ts. Do not edit.
// From project.godot (Godot's defaults where it sets nothing). Change it in Godot's Project Settings, not here.
export const Project = { viewport: { width: 1152, height: 648 } } as const;

export const Textures = {
  ball: "res://art/ball.png",
  paddle: "res://art/paddle.png",
} as const;
export type TexturePath = (typeof Textures)[keyof typeof Textures];

export const Scenes = {
  main: "res://main.tscn",
} as const;
export type ScenePath = (typeof Scenes)[keyof typeof Scenes];

export const Scripts = {
  ball: "res://scripts/ball.gd",
} as const;
export type ScriptPath = (typeof Scripts)[keyof typeof Scripts];
