// Questions the validator asks about Godot's classes, answered from data/classes.json
// (generated by tools/gen-classes.ts from Godot's own API dump).

import data from "../data/classes.json" with { type: "json" };

type ClassInfo = { inherits: string | null; instantiable: boolean };

const CLASSES: Record<string, ClassInfo> = data.classes;
export const GODOT_VERSION: string = data.godot;

// Object.hasOwn, not `name in CLASSES`: a type called "constructor" must not count as a Godot class.
export const exists = (name: string): boolean => typeof name === "string" && Object.hasOwn(CLASSES, name);

export const isInstantiable = (name: string): boolean => exists(name) && CLASSES[name].instantiable;

// Is `name` the same class as `ancestor`, or a subclass of it? Walks the `inherits` chain upwards.
export function isA(name: string, ancestor: string): boolean {
  let current: string | null = exists(name) ? name : null;
  for (let steps = 0; current !== null && steps < 100; steps++) {
    if (current === ancestor) return true;
    current = CLASSES[current].inherits;
  }
  return false;
}

// For an error message: what kind of thing is this class, if it is not a Node?
export function familyOf(name: string): string {
  if (isA(name, "Resource")) return "Resource";
  if (isA(name, "RefCounted")) return "RefCounted object";
  return "Object";
}

// Concrete classes that extend `name` directly, for "use one of these instead" hints.
export function concreteSubclasses(name: string): string[] {
  return Object.keys(CLASSES).filter((c) => CLASSES[c].inherits === name && CLASSES[c].instantiable);
}

// ---- "did you mean ...?" for typos -----------------------------------------------------------------

// Plain edit distance: how many single-character inserts, deletes or changes turn `a` into `b`.
function distance(a: string, b: string): number {
  let previous = Array.from({ length: b.length + 1 }, (_, j) => j);
  for (let i = 1; i <= a.length; i++) {
    const current = [i];
    for (let j = 1; j <= b.length; j++) {
      const change = a[i - 1] === b[j - 1] ? 0 : 1;
      current[j] = Math.min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + change);
    }
    previous = current;
  }
  return previous[b.length];
}

// The closest instantiable Node class within 2 edits (case ignored), or null. Ties go to the alphabetically first.
export function didYouMean(typed: string): string | null {
  if (typeof typed !== "string" || typed === "") return null;
  let best: string | null = null;
  let bestDistance = 3;
  for (const name of Object.keys(CLASSES)) {
    if (!CLASSES[name].instantiable || !isA(name, "Node")) continue;
    const d = distance(typed.toLowerCase(), name.toLowerCase());
    if (d < bestDistance) {
      best = name;
      bestDistance = d;
    }
  }
  return best;
}
