// Regenerates two small files from Godot's own API dump, so the validator knows Godot's class hierarchy:
//   data/classes.json         class name -> { inherits, instantiable }        (read by the validator at run time)
//   src/node-types.gen.ts     `NodeType`: a union of every instantiable Node class   (used by SceneNode.type)
// The 7 MB dump itself is written to a temp folder and thrown away; it is never put in the repo.
//
// Usage: node tools/gen-classes.ts [--godot <path to godot binary>] [--api <existing extension_api.json>]

import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

type ApiClass = { name: string; inherits?: string; is_instantiable: boolean };

const args = process.argv.slice(2);
const option = (flag: string) => (args.includes(flag) ? args[args.indexOf(flag) + 1] : undefined);

// ---- 1. get the API dump (run godot, or reuse a dump you already have) ---------------------------

let dumpDir: string | undefined;
let apiFile = option("--api");

if (!apiFile) {
  const godot = option("--godot") ?? "godot";
  dumpDir = mkdtempSync(join(tmpdir(), "gen-classes-"));
  const run = spawnSync(godot, ["--headless", "--dump-extension-api"], { cwd: dumpDir, encoding: "utf8" });
  apiFile = join(dumpDir, "extension_api.json");
  if (run.error || !existsSync(apiFile)) {
    console.error(`could not run "${godot} --headless --dump-extension-api": ${run.error?.message ?? run.stderr}`);
    process.exit(1);
  }
}

const api = JSON.parse(readFileSync(apiFile, "utf8"));
if (dumpDir) rmSync(dumpDir, { recursive: true, force: true });

const version: string = api.header.version_full_name;
const classes: ApiClass[] = [...api.classes].sort((a: ApiClass, b: ApiClass) => (a.name < b.name ? -1 : 1));
const byName = new Map(classes.map((c) => [c.name, c]));

// ---- 2. data/classes.json: one class per line, so diffs between Godot versions are readable --------

const classLines = classes.map(
  (c) => `    ${JSON.stringify(c.name)}: { "inherits": ${JSON.stringify(c.inherits ?? null)}, "instantiable": ${c.is_instantiable} }`,
);
const json = `{\n  "godot": ${JSON.stringify(version)},\n  "classes": {\n${classLines.join(",\n")}\n  }\n}\n`;

// ---- 3. src/node-types.gen.ts: every instantiable class that descends from Node ------------------

function descendsFromNode(name: string): boolean {
  for (let cur: string | undefined = name; cur; cur = byName.get(cur)?.inherits) {
    if (cur === "Node") return true;
  }
  return false;
}

const nodeTypes = classes.filter((c) => c.is_instantiable && descendsFromNode(c.name)).map((c) => c.name);
const ts =
  `// AUTO-GENERATED by tools/gen-classes.ts from ${version}. Do not edit.\n` +
  `// Every Godot class that can be created with .new() and descends from Node.\n` +
  `export type NodeType =\n${nodeTypes.map((n) => `  | ${JSON.stringify(n)}`).join("\n")};\n`;

// ---- 4. write, but only when the text changed (so watchers are not retriggered) --------------------

function writeIfChanged(url: URL, text: string) {
  const path = fileURLToPath(url);
  if (existsSync(path) && readFileSync(path, "utf8") === text) console.log(`unchanged ${path}`);
  else {
    writeFileSync(path, text);
    console.log(`wrote ${path} (${text.length} bytes)`);
  }
}

writeIfChanged(new URL("../data/classes.json", import.meta.url), json);
writeIfChanged(new URL("../src/node-types.gen.ts", import.meta.url), ts);
console.log(`${version}: ${classes.length} classes, ${nodeTypes.length} instantiable node types`);
